version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  postgres_data:
