version: '3.9'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    restart: always
    build: ./
    command: celery -A simple_cms worker -l info
    volumes:
      - ./:/usr/src/simple_cms/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn simple_cms.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - media_volume:/home/django/simple_cms/media
    depends_on:
      - db
      - celery
      - redis
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - media_volume:/home/django/simple_cms/media
    depends_on:
      - web
volumes:
  postgres_data:
  media_volume:

