# Generated by Django 4.1 on 2022-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='object_fit',
            field=models.CharField(choices=[('fill', 'Fill'), ('contain', 'Contain'), ('cover', 'Cover'), ('none', 'None'), ('scale-down', 'Scale Down')], default='contain', max_length=10),
        ),
    ]
