# Generated by Django 4.1 on 2022-08-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_block_effect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='text',
            new_name='html',
        ),
    ]
