# Generated by Django 4.1 on 2022-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_block_color_remove_block_font_bold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='background',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
